[workspace]
members = ["wg-proto", "wg-rust-crypto", "wg"]
resolver = "2"
default-members = ["wg"]

[profile.release]
overflow-checks = true
incremental = false
codegen-units = 1
opt-level = 3
debug = "full"
strip = true
lto = true
